package com.view;

import com.dao.PersonagemDAO;
import com.projetoopoo.Personagens;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pesquisarIDLabel = new javax.swing.JLabel();
        buttonPesquisar = new javax.swing.JButton();
        nomeLabel = new javax.swing.JLabel();
        categoriaLabel = new javax.swing.JLabel();
        recompensaLabel = new javax.swing.JLabel();
        frutaLabel = new javax.swing.JLabel();
        arcoLabel = new javax.swing.JLabel();
        pesquisarIDField = new javax.swing.JTextField();
        nomeField = new javax.swing.JTextField();
        categoriaField = new javax.swing.JTextField();
        recompensaField = new javax.swing.JTextField();
        frutaField = new javax.swing.JTextField();
        arcoField = new javax.swing.JTextField();
        buttonEditar = new javax.swing.JButton();
        buttonCadastrar = new javax.swing.JButton();
        buttonExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPersonagens = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\jonhl\\OneDrive\\Área de Trabalho\\poo\\OnePieceLogo.png")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        pesquisarIDLabel.setText("Pesquisar ID:");

        buttonPesquisar.setBackground(new java.awt.Color(153, 153, 153));
        buttonPesquisar.setText("Pesquisar");
        buttonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPesquisarActionPerformed(evt);
            }
        });

        nomeLabel.setText("Nome:");

        categoriaLabel.setText("Categoria:");

        recompensaLabel.setText("Recompensa:");

        frutaLabel.setText("Fruta:");

        arcoLabel.setText("Arco:");

        pesquisarIDField.setBackground(new java.awt.Color(204, 204, 204));
        pesquisarIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarIDFieldActionPerformed(evt);
            }
        });

        nomeField.setBackground(new java.awt.Color(204, 204, 204));

        categoriaField.setBackground(new java.awt.Color(204, 204, 204));
        categoriaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriaFieldActionPerformed(evt);
            }
        });

        recompensaField.setBackground(new java.awt.Color(204, 204, 204));

        frutaField.setBackground(new java.awt.Color(204, 204, 204));

        arcoField.setBackground(new java.awt.Color(204, 204, 204));
        arcoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arcoFieldActionPerformed(evt);
            }
        });

        buttonEditar.setBackground(new java.awt.Color(153, 153, 153));
        buttonEditar.setText("Atualizar");
        buttonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarActionPerformed(evt);
            }
        });

        buttonCadastrar.setBackground(new java.awt.Color(153, 153, 153));
        buttonCadastrar.setText("Cadastrar");
        buttonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarActionPerformed(evt);
            }
        });

        buttonExcluir.setBackground(new java.awt.Color(153, 153, 153));
        buttonExcluir.setText("Excluir");
        buttonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluirActionPerformed(evt);
            }
        });

        tabelaPersonagens.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                },
                new String [] {
                        "ID", "Nome", "Categoria", "Recompensa", "Fruta", "Arco"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                    false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaPersonagens);
        if (tabelaPersonagens.getColumnModel().getColumnCount() > 0) {
            tabelaPersonagens.getColumnModel().getColumn(0).setResizable(false);
            tabelaPersonagens.getColumnModel().getColumn(1).setResizable(false);
            tabelaPersonagens.getColumnModel().getColumn(2).setResizable(false);
            tabelaPersonagens.getColumnModel().getColumn(3).setResizable(false);
            tabelaPersonagens.getColumnModel().getColumn(4).setResizable(false);
            tabelaPersonagens.getColumnModel().getColumn(5).setResizable(false);
        }


        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(193, 193, 193)
                                                .addComponent(jLabel7))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(pesquisarIDLabel)
                                                        .addComponent(nomeLabel)
                                                        .addComponent(categoriaLabel)
                                                        .addComponent(recompensaLabel)
                                                        .addComponent(frutaLabel)
                                                        .addComponent(arcoLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(buttonPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(pesquisarIDField)
                                                        .addComponent(nomeField, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(categoriaField)
                                                        .addComponent(arcoField)
                                                        .addComponent(frutaField)
                                                        .addComponent(recompensaField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(30, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(buttonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7)
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                                        .addComponent(pesquisarIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(pesquisarIDLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(buttonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(31, 31, 31)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                                        .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(nomeLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                                        .addComponent(categoriaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(categoriaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                                        .addComponent(recompensaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(recompensaLabel))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                                        .addComponent(frutaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(frutaLabel))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                                        .addComponent(arcoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(arcoLabel)))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(buttonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(buttonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(buttonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void pesquisarIDFieldActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void buttonEditarActionPerformed(java.awt.event.ActionEvent evt) {
        String nome = nomeField.getText();
        String categoria = categoriaField.getText();
        Double recompensa = Double.valueOf(recompensaField.getText());
        String fruta = frutaField.getText();
        String arco = arcoField.getText();
        Integer id = Integer.valueOf(pesquisarIDField.getText());

        PersonagemDAO personagemDao = new PersonagemDAO();

        Personagens personagens = new Personagens();

        personagens.setNome(nome);
        personagens.setCategoria(categoria);
        personagens.setRecompensa(recompensa);
        personagens.setFruta(fruta);
        personagens.setArcoEntrou(arco);
        personagens.setIdPersonagem(id);

        personagemDao.edit(personagens);

        JOptionPane.showMessageDialog(null, "Personagem atualizado com sucesso!");

        preencherTabela();
    }

    private void categoriaFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void arcoFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void buttonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {
        int idPesquisa = Integer.parseInt(pesquisarIDField.getText());
        PersonagemDAO personagemDAO = new PersonagemDAO();
        Personagens personagens = personagemDAO.buscar(idPesquisa);

        nomeField.setText(personagens.getNome());
        categoriaField.setText(personagens.getCategoria());
        recompensaField.setText(String.valueOf(personagens.getReconpensa()));
        frutaField.setText(personagens.getFruta());
        arcoField.setText(personagens.getArcoEntrou());
    }

    private void buttonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {
        String nome = nomeField.getText();
        String categoria = categoriaField.getText();
        Double recompensa = Double.valueOf(recompensaField.getText());
        String fruta = frutaField.getText();
        String arco = arcoField.getText();

        PersonagemDAO personagemDao = new PersonagemDAO();

        Personagens personagens = new Personagens();
        personagens.setNome(nome);
        personagens.setCategoria(categoria);
        personagens.setRecompensa(recompensa);
        personagens.setFruta(fruta);
        personagens.setArcoEntrou(arco);

        personagemDao.create(personagens);

        JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!");

        preencherTabela();
    }

    private void buttonExcluirActionPerformed(java.awt.event.ActionEvent evt) {
        int idDeletar = Integer.parseInt(pesquisarIDField.getText());
        PersonagemDAO personagemDao = new PersonagemDAO();
        Personagens personagem = personagemDao.delete(idDeletar);

        preencherTabela();
    }

    public static void preencherTabela(){
        DefaultTableModel model = (DefaultTableModel) tabelaPersonagens.getModel();
        model.setNumRows(0);

        Object colunas[] = new Object[6];

        Personagens personagens = new Personagens();

        ArrayList<Personagens> listaDePersonagens = new ArrayList<Personagens>();

        listaDePersonagens = (ArrayList<Personagens>) PersonagemDAO.listarPersonagens();

        for(int i = 0; i < listaDePersonagens.size(); i++){
            personagens = listaDePersonagens.get(i);

            colunas[0] = personagens.getIdPersonagem();
            colunas[1] = personagens.getNome();
            colunas[2] = personagens.getCategoria();
            colunas[3] = personagens.getReconpensa();
            colunas[4] = personagens.getFruta();
            colunas[5] = personagens.getArcoEntrou();

            model.addRow(colunas);
        }
    }

    // Variables declaration - do not modify
    private javax.swing.JTextField arcoField;
    private javax.swing.JLabel arcoLabel;
    private javax.swing.JButton buttonCadastrar;
    private javax.swing.JButton buttonEditar;
    private javax.swing.JButton buttonExcluir;
    private javax.swing.JButton buttonPesquisar;
    private javax.swing.JTextField categoriaField;
    private javax.swing.JLabel categoriaLabel;
    private javax.swing.JTextField frutaField;
    private javax.swing.JLabel frutaLabel;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomeField;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JTextField pesquisarIDField;
    private javax.swing.JLabel pesquisarIDLabel;
    private javax.swing.JTextField recompensaField;
    private javax.swing.JLabel recompensaLabel;
    private static javax.swing.JTable tabelaPersonagens;
    // End of variables declaration
}

